### ISSUE TITLE
Move on to Java 8

### ISSUE THREAD

**Issue by brunoborges** [oracle/soda-for-java#2]
Are there plans to move to Java 8?

**Comment by morgiyan** [comment]
Hi Bruno, 

If you mean compiling and running SODA with Java 8, that works. Released jars work with Java 8 as well. 

Thanks,
Max.

**Comment by brunoborges** [comment]
I am saying more like changing the default build configuration to work with Java 8 by default, instead of requiring developers to download Java 6 in order to build. The process to build SODA from the sources is not well documented.
          
            
            On May 29 2017, at 10:45 pm, Maxim Orgiyan <notifications@github.com> wrote:
            
            
              Hi Bruno,
If you mean compiling and running SODA with Java 8, that works. Released jars work with Java 8 as well.
Thanks,
Max.

**Comment by morgiyan** [comment]
We have detailed documentation on compiling the sources here:

https://github.com/oracle/soda-for-java/blob/master/doc/Building-source-code.md

If you set JAVA6HOME env variable mentioned in the instructions to JDK 8, it will compile with Java 8.

I will update the build files and instructions so that they are JDK independent (i.e. so that they don't refer to Java 6 specifically).

**Comment by morgiyan** [comment]
Building has been updated to work with any JDK, 6 or above. 

Updated instructions:

https://github.com/oracle/soda-for-java/blob/master/doc/Building-source-code.md
