### ISSUE TITLE
There is no field type indicator therefore it's not possible sort by number

### ISSUE THREAD

**Issue by vweng** [oracle/soda-for-java#3]
If a field stores number only, the result of $sort on that field still comes out in alphabetical. e.g. Sort order becomes 1, 100, 2, 20, 3 ... etc.
Where it should be 1,2,3,20,100 etc.

We are using SODA 1.0.4.

**Comment by morgiyan** [comment]
Sorry for the delayed response, missed seeing this issue till now.

We are working on adding this feature (along with a number of others). 
There will be additional syntax to specify the type (e.g. number) to the 
$orderby operator.

By default, scalar values are sorted as strings (even if they are numbers, they
are converted to strings for sorting), which is the current behavior you're 
seeing.

**Comment by vweng** [comment]
Has this issue been fixed in the new 1.0.5 release?

It'd be grateful to see a change log for each release instead of being left blind during upgrade.

**Comment by morgiyan** [comment]
Hi Victor,

1.0.5 does not have the orderby change you requested. That release
was primarily for keyLike feature requested earlier by someone else. We are
working on another release which will have multiple new features, 
including the improved orderby support that will do what you requested. I will reply
here once that release is out, so that you get a notification.

On releases page, for each release there's "This release contains the following features"
and "This release contains the following bug fixes" info. So I think it should provide the change log info you're looking for.

Any additional comments/questions - please let me know.

Thanks,
Max.

**Comment by morgiyan** [comment]
Hi Victor,

The issue has been fixed in 1.1.0. See "Using the Orderby Clause Array Syntax" subsection [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/adsdi/overview-soda-filter-specifications-qbes.html#GUID-3B182089-9A38-45DA-B7D7-8232E13C8F83) and "Orderby Clause Array Syntax" [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/adsdi/soda-filter-specifications-reference.html#GUID-8AD6237B-860C-43A7-B6B7-5C8328784322). 

The array syntax for the orderby clause allows you to specify 'number' as the datatype.

Please give it a try and let us know if you see any issues.

Thank you!
Max.
